resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr
- name: copr
  type: docker-image
  source:
    repository: quay.io/ahoi/concourse-copr-resource

resources:
- name: git-clone-resource
  type: git
  source:
    branch: master
    uri: https://github.com/drahnr/oregano.git

# - name: git-tag-resource
#   type: git
#   source:
#     tag_filter: "v[0-9]*.[0-9]*{,.[0-9]*}"
#     branch: master
#     uri: https://github.com/drahnr/oregano.git

- name: git-pull-request-resource
  type: pull-request
  source:
    repo: drahnr/oregano
    access_token: {{github-token}}


- name: copr-resource
  type: copr
  source:
    login: {{copr-login}}
    token: {{copr-token}}
    url: {{copr-url}}

- name: oregano-test-fedora
  type: docker-image
  source:
    repository: quay.io/ratpoison/oregano-test-fedora
    username: {{quay-username}}
    password: {{quay-password}}

- name: oregano-test-ubuntu
  type: docker-image
  source:
    repository: quay.io/ratpoison/oregano-test-ubuntu
    username: {{quay-username}}
    password: {{quay-password}}

- name: deb-rc
  type: s3
  source:
    endpoint: https://minio.spearow.io
    bucket: oregano-rc
    regexp: (.*).deb
    access_key_id: {{minio-access-key}}
    secret_access_key: {{minio-secret-key}}

- name: rpm-rc
  type: s3
  source:
    endpoint: https://minio.spearow.io
    bucket: oregano-rc
    regexp: (.*).rpm
    access_key_id: {{minio-access-key}}
    secret_access_key: {{minio-secret-key}}

- name: source-rc
  type: s3
  source:
    endpoint: https://minio.spearow.io
    bucket: oregano-rc
    regexp: (.*).tar.xz
    access_key_id: {{minio-access-key}}
    secret_access_key: {{minio-secret-key}}

- name: deb-drop
  type: s3
  source:
    endpoint: https://minio.spearow.io
    bucket: oregano-drop
    regexp: (.*).deb
    access_key_id: {{minio-access-key}}
    secret_access_key: {{minio-secret-key}}

- name: rpm-drop
  type: s3
  source:
    endpoint: https://minio.spearow.io
    bucket: oregano-drop
    regexp: (.*).rpm
    access_key_id: {{minio-access-key}}
    secret_access_key: {{minio-secret-key}}

- name: source-drop
  type: s3
  source:
    endpoint: https://minio.spearow.io
    bucket: oregano-drop
    regexp: (.*).tar.xz
    access_key_id: {{minio-access-key}}
    secret_access_key: {{minio-secret-key}}

- name: gh-release
  type: github-release
  source:
    owner: drahnr
    repository: oregano

jobs:
  - name: pr-compile
    build_logs_to_retain: 50
    public: true
    plan:
    - aggregate:
      - get: oregano-test-fedora
        trigger: true
      - get: git-pull-request-resource
        trigger: true
    - task: compile
      timeout: 5m
      image: oregano-test-fedora
      config:
        platform: linux
        inputs:
        - name: git-pull-request-resource
        run:
          path: sh
          args:
          - -exc
          - |
            ./waf configure build --debug --prefix=/tmp install
            ./build/test/microtests
          dir: "git-pull-request-resource"
      on_success:
        put: git-pull-request-resource
        params:
          path: git-pull-request-resource
          status: success
      on_failure:
        put: git-pull-request-resource
        params:
          path: git-pull-request-resource
          status: failure

  - name: compile
    build_logs_to_retain: 10
    public: true
    plan:
    - aggregate:
      - get: oregano-test-fedora
        trigger: true
      - get: git-clone-resource
        trigger: true

    - task: compile
      timeout: 15m
      image: oregano-test-fedora
      config:
        platform: linux
        inputs:
        - name: git-clone-resource
        outputs:
        - name: dist
        run:
          path: sh
          args:
          - -exc
          - |
            ./waf configure build --debug --prefix=/tmp install
            ./build/test/microtests && echo "tests passed" || cat ./build/test/test.log
            ./waf dist
            cp oregano-*.tar.xz ../dist/
          dir: git-clone-resource

    - put: source-drop
      params:
        file: dist/oregano-*.tar.xz
        acl: public-read

  - name: build-pkg-rpm
    build_logs_to_retain: 5
    public: true
    plan:
    - aggregate:
      - get: oregano-test-fedora
        trigger: true
      - get: git-clone-resource
        trigger: true
        passed: [compile]

    - task: create-rpm
      timeout: 10m
      image: oregano-test-fedora
      config:
        platform: linux
        inputs:
        - name: git-clone-resource
        outputs:
        - name: srpm
        - name: rpm
        run:
          path: ./.concourse/fedora/buildrpm.sh
          args: [ .. ]
          dir: git-clone-resource

    - put: rpm-drop
      params:
        file: rpm/oregano*.rpm
        acl: public-read

    - put: copr
      resource: copr-resource
      params:
        rpmbuild_dir: "srpm"
        chroots: ["fedora-rawhide-x86_64", "fedora-26-x86_64", "fedora-25-x86_64"]
        enable_net: false
        max_n_bytes: 250000000
        project_id: 825
        regex: ".*oregano-.*\\.src\\.rpm$"

  - name: build-pkg-deb
    build_logs_to_retain: 5
    public: true
    plan:
    - aggregate:
      - get: oregano-test-ubuntu
        trigger: true
      - get: git-clone-resource
        trigger: true
        passed: [compile]

    - task: create-deb
      timeout: 10m
      image: oregano-test-ubuntu
      config:
        platform: linux
        inputs:
        - name: git-clone-resource
        outputs:
        - name: deb
        run:
          path: sh
          args:
          - -exc
          - |
            debuild -i -us -uc -b
            ls -al ..
            cp ../oregano*.deb ../deb/
          dir: git-clone-resource

    - put: deb-drop
      params:
        file: deb/oregano*.deb
        acl: public-read

  - name: pr-build-pkg-rpm
    build_logs_to_retain: 5
    public: true
    plan:
    - aggregate:
      - get: oregano-test-fedora
        trigger: true
      - get: git-pull-request-resource
        trigger: true
        passed: [pr-compile]

    - task: create-rpm
      timeout: 10m
      image: oregano-test-fedora
      config:
        platform: linux
        inputs:
        - name: git-pull-request-resource
        run:
          path: .concourse/fedora/buildrpm.sh
          dir: git-pull-request-resource

  - name: pr-build-pkg-deb
    build_logs_to_retain: 5
    public: true
    plan:
    - aggregate:
      - get: oregano-test-ubuntu
        trigger: true
      - get: git-pull-request-resource
        trigger: true
        passed: [pr-compile]

    - task: create-deb
      timeout: 10m
      image: oregano-test-ubuntu
      config:
        platform: linux
        inputs:
        - name: git-pull-request-resource
        run:
          path: debuild
          args: ["-i", "-us", "-uc", "-b"]
          dir: git-pull-request-resource

  - name: make-rc
    build_logs_to_retain: 5
    public: true
    plan:
    - aggregate:
      - get: source-drop
        trigger: true
      - get: rpm-drop
        trigger: true
      - get: deb-drop
        trigger: true
    - task: tag2file
      timeout: 5m
      image: oregano-test-fedora
      config:
        platform: linux
        inputs:
        - name: source-drop
        - name: deb-drop
        - name: rpm-drop
        outputs:
        - name: source-rc
        - name: deb-rc
        - name: rpm-rc
        run:
          path: sh
          args:
          - -exc
          - |
            cp source-drop/* source-release/
            cp deb-drop/* deb-release/
            cp rpm-drop/* rpm-release/
    - put: source-rc
      params:
        file: oregano-*.tar.xz
        acl: public-read
    - put: deb-rc
      params:
        file: oregano-*.deb
        acl: public-read
    - put: rpm-rc
      params:
        file: oregano-*.rpm
        acl: public-read

  - name: make-release
    build_logs_to_retain: 5
    public: true
    plan:
    - aggregate:
      - get: source-rc
      - get: rpm-rc
      - get: deb-rc
      passed: [compile, build-pkg-deb, build-pkg-rpm]
    - task: tag2file
      timeout: 5m
      image: oregano-test-fedora
      config:
        platform: linux
        inputs:
        - name: git-tag-resource
        - name: source-rc
        - name: deb-rc
        - name: rpm-rc
        outputs:
        - name: release-info
        run:
          path: sh
          args:
          - -exc
          - |
            git tag -l --points-at HEAD > ../release-info/TAG
            echo "oregano" > ../release-info/NAME
            echo "Yet another release" > ../release-info/BODY
          dir: git-tag-resource
    - put: gh-release
      params:
        name: release-info/NAME
        tag: release-info/TAG
        body: release-info/BODY
        globs:
        - source-rc/oregano-*.tar.xz
        - rpm-rc/oregano-*.rpm
        - deb-rc/oregano-*.deb
      
